// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package activity

import (
	"voichatter/api/activity"
)

type ControllerV1 struct{}

func NewV1() activity.IActivityV1 {
	return &ControllerV1{}
}
