// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package server

import (
	"voichatter/api/server"
)

type ControllerV1 struct{}

func NewV1() server.IServerV1 {
	return &ControllerV1{}
}
