// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"voichatter/internal/dao/internal"
)

// internalChannelDao is internal type for wrapping internal DAO implements.
type internalChannelDao = *internal.ChannelDao

// channelDao is the data access object for table channel.
// You can define custom methods on it to extend its functionality as you wish.
type channelDao struct {
	internalChannelDao
}

var (
	// Channel is globally public accessible object for table channel operations.
	Channel = channelDao{
		internal.NewChannelDao(),
	}
)

// Fill with you ideas below.
