// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package qiniu

import (
	"voichatter/api/qiniu"
)

type ControllerV1 struct{}

func NewV1() qiniu.IQiniuV1 {
	return &ControllerV1{}
}
